import 'package:flutter/material.dart';
import 'package:fortune_wheel/core/config/config.dart';
import 'package:fortune_wheel/fortune_wheel/presentation/pages/admin_panel.dart';

void main() async{
  await Config.mainConfig();
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      debugShowCheckedModeBanner: false,
      home: AdminPanel(),
    );
  }
}

// 1. To setup hive => add the hive.initFlutter
// 2. Create model class with hive :
// ==> Modify Model class
// ==> Generate Model Adapter
// ==> Register Model Adapter
// ==>  for generate : flutter pub get && flutter pub run build_runner build --delete-conflicting-outputs
// 3. When you generate you should make the Adapter generated by hive in the main function
// 4. open the box

